# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "git-pivotal-tracker"
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zach Dennis", "Jeff Tucker", "Sam Stokes"]
  s.date = "2012-04-01"
  s.description = "A collection of git utilities to ease integration with Pivotal Tracker."
  s.email = "zach.dennis@gmail.com"
  s.executables = ["git-accept", "git-block", "git-finish", "git-info", "git-start", "git-unblock"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "Rakefile",
    "VERSION",
    "bin/git-accept",
    "bin/git-block",
    "bin/git-finish",
    "bin/git-info",
    "bin/git-start",
    "bin/git-unblock",
    "features/accept.feature",
    "features/block.feature",
    "features/finish.feature",
    "features/info.feature",
    "features/start.feature",
    "features/step_definitions/steps.rb",
    "features/support/dsl/assertions.rb",
    "features/support/dsl/data.rb",
    "features/support/dsl/pivotal.rb",
    "features/support/env.rb",
    "features/support/git-pivotal.rb",
    "features/test_repo/origin.git/COMMIT_EDITMSG",
    "features/test_repo/origin.git/HEAD",
    "features/test_repo/origin.git/config",
    "features/test_repo/origin.git/description",
    "features/test_repo/origin.git/hooks/applypatch-msg.sample",
    "features/test_repo/origin.git/hooks/commit-msg.sample",
    "features/test_repo/origin.git/hooks/post-commit.sample",
    "features/test_repo/origin.git/hooks/post-receive.sample",
    "features/test_repo/origin.git/hooks/post-update.sample",
    "features/test_repo/origin.git/hooks/pre-applypatch.sample",
    "features/test_repo/origin.git/hooks/pre-commit.sample",
    "features/test_repo/origin.git/hooks/pre-rebase.sample",
    "features/test_repo/origin.git/hooks/prepare-commit-msg.sample",
    "features/test_repo/origin.git/hooks/update.sample",
    "features/test_repo/origin.git/index",
    "features/test_repo/origin.git/info/exclude",
    "features/test_repo/origin.git/logs/HEAD",
    "features/test_repo/origin.git/logs/refs/heads/master",
    "features/test_repo/origin.git/objects/0c/6f7b1384910d1a2f137590095f008a06c7e00c",
    "features/test_repo/origin.git/objects/10/ecf2b7ce989f01f3f7266e712b48d9275f2635",
    "features/test_repo/origin.git/objects/a5/71d56305df09fb060f6ccb730b46080d305beb",
    "features/test_repo/origin.git/refs/heads/master",
    "features/test_repo/readme",
    "features/unblock.feature",
    "lib/commands/accept.rb",
    "lib/commands/base.rb",
    "lib/commands/block.rb",
    "lib/commands/bug.rb",
    "lib/commands/card.rb",
    "lib/commands/chore.rb",
    "lib/commands/feature.rb",
    "lib/commands/finish.rb",
    "lib/commands/info.rb",
    "lib/commands/map.rb",
    "lib/commands/pick.rb",
    "lib/commands/start.rb",
    "lib/commands/unblock.rb",
    "readme.markdown",
    "spec/commands/base_spec.rb",
    "spec/commands/bug_spec.rb",
    "spec/commands/chore_spec.rb",
    "spec/commands/feature_spec.rb",
    "spec/commands/finish_spec.rb",
    "spec/commands/map_spec.rb",
    "spec/commands/start_spec.rb",
    "spec/factories.rb",
    "spec/factory.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/zdennis/git-pivotal"
  s.post_install_message = "If you haven't set up git-pivotal-tracker before, here's a few commands to \nget started:\n\n   # Applies to global Git configuration\n   git config --global pivotal.api-token <your-token-here>\n   git config --global pivotal.full-name \"Your Name As In Pivotal\"\n\n   # Applies to project-specific Git configuration\n   git config -f .git/config pivotal.project-id <pivotal-project-id>\n\n"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A collection of git utilities to ease integration with Pivotal Tracker."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      puts "HERE1"
      s.add_runtime_dependency(%q<git-pivotal-tracker>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<pivotal-tracker>, ["~> 0.5.1"])
    else
      puts "HERE2"
      s.add_dependency(%q<git-pivotal-tracker>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<pivotal-tracker>, ["~> 0.5.1"])
    end
  else
        puts "HERE3"  
    s.add_dependency(%q<git-pivotal-tracker>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<pivotal-tracker>, ["~> 0.5.1"])
  end
end

