require 'mocha'
require 'builder'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.mock_with :mocha
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

specdir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
require File.join(specdir, 'lib','git-pivotal-tracker')

require File.join(File.dirname(__FILE__), 'factories')

def stub_connection_to_pivotal
  RestClient::Resource.any_instance.stubs(:get).returns("")
end
